[features]
seeds = false
skip-lint = false
[programs.localnet]
solbook = "BgjKF9nf4SyUpqWcB5Y8go9dumRRR3ZsuhffcXGxbAMu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/macbookpro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
